[package]
name = "airpodsbattery"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bluest = "0.5.3"
tracing = "0.1.37"
tokio = {version = "1.32.0", features = ["full"]}